# Author: Elisha Roberson
# Edited: 2024-10-23
#
# Software:
# MACS2
FROM thatdnaguy/ubuntu_general:latest

RUN apt update && \ 
    apt install -y \
        python3-dev \
        build-essential && \
    pip3 install macs2==2.2.9.1

