# Author: Elisha Roberson
# Edited: 2024-03-19
#
# Software:
# multiqc
FROM thatdnaguy/ubuntu_general:latest

RUN apt install -y libjpeg-dev zlib1g-dev && \
    pip3 install Pillow && \
    pip3 install multiqc==1.21
