# Author: Elisha Roberson
# Edited: 2024-12-06
#
# Software:
# scSplit

# start with our ubuntu image
FROM thatdnaguy/ubuntu_general:latest

RUN [ "pip3", "install", "numpy", "pandas", "pysam", "PyVCF", "scikit-learn", "scipy", "statistics" ]

RUN [ "pip3", "install", "scSplit" ]

